"use client";

import Link from "next/link";
import { ReactNode, useEffect, useMemo, useState } from "react";
import UnifiedShell from "@/components/UnifiedShell";
import { supabase } from "@/lib/supabase";

type Row=Record<string,any>; type View="folders"|"boxes"|"transfers"|"retention";
const date=(v:any)=>v?new Intl.DateTimeFormat("es-CO",{dateStyle:"medium"}).format(new Date(v)):"—";
function Icon({name}:{name:"folder"|"box"|"transfer"|"clock"|"archive"}){const p:Record<string,ReactNode>={folder:<><path d="M3.5 7.5h6l2-2h9v13h-17z"/><path d="M3.5 9h17"/></>,box:<><path d="M4 7h16v13H4z"/><path d="M3 4h18v4H3zM9 12h6"/></>,transfer:<><path d="M5 8h13M15 5l3 3-3 3M19 16H6M9 13l-3 3 3 3"/></>,clock:<><circle cx="12" cy="12" r="8.5"/><path d="M12 7v5l3 2"/></>,archive:<><path d="M6 5h12v14H6z"/><path d="M9 9h6M9 13h6"/></>};return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{p[name]}</svg>}

export default function ArchiveCenter(){
 const [view,setView]=useState<View>("folders"); const [folders,setFolders]=useState<Row[]>([]); const [boxes,setBoxes]=useState<Row[]>([]); const [transfers,setTransfers]=useState<Row[]>([]); const [retention,setRetention]=useState<Row[]>([]); const [q,setQ]=useState("");
 useEffect(()=>{(async()=>{const v=new URLSearchParams(window.location.search).get("vista"); if(v==="transferencias")setView("transfers");const [f,b,t,r]=await Promise.all([supabase.from("archive_folders").select("*,archive_boxes(box_number,phase),expedientes(id,expediente_code,title,status,organizational_units(name),trd_entries(name))").order("created_at",{ascending:false}).limit(500),supabase.from("archive_boxes").select("*,physical_locations(name,code)").order("created_at",{ascending:false}).limit(400),supabase.from("transfers").select("*,organizational_units(name)").order("transfer_date",{ascending:false}).limit(400),supabase.from("expedientes").select("id,expediente_code,title,status,phase,retention_management_due,retention_central_due,disposition_due,disposition,organizational_units(name),trd_entries(name)").or("retention_management_due.not.is.null,retention_central_due.not.is.null,disposition_due.not.is.null").order("retention_management_due",{ascending:true,nullsFirst:false}).limit(500)]);setFolders(f.data||[]);setBoxes(b.data||[]);setTransfers(t.data||[]);setRetention(r.data||[]);})()},[]);
 const filter=(rows:Row[])=>{const s=q.trim().toLowerCase();return !s?rows:rows.filter(x=>JSON.stringify(x).toLowerCase().includes(s))};
 const counts=useMemo(()=>({folders:folders.length,boxes:boxes.length,transfers:transfers.length,retention:retention.length,unboxed:folders.filter(x=>!x.archive_boxes?.box_number).length,unlocated:boxes.filter(x=>!x.physical_locations?.name).length}),[folders,boxes,transfers,retention]);
 const phaseCounts=useMemo(()=>({management:boxes.filter(x=>x.phase==="management").length,central:boxes.filter(x=>x.phase==="central").length,historical:boxes.filter(x=>x.phase==="historical").length}),[boxes]);
 const title={folders:"Carpetas organizadas",boxes:"Cajas de archivo",transfers:"Transferencias documentales",retention:"Retención y disposición"}[view];
 const desc={folders:"Consulta ubicación, expediente, TRD y folios de cada carpeta.",boxes:"Controla fase, ubicación física e identificación de cada caja.",transfers:"Sigue los movimientos entre gestión, central e histórico.",retention:"Revisa las fechas calculadas y la disposición documental."}[view];
 return <UnifiedShell eyebrow="ARCHIVO" title="Archivo y conservación" actions={<Link className="ui-btn yellow" href="/trabajo/organizar">Organizar expediente</Link>}>
  <div className="module-stack">
   <section className="module-hero"><div className="module-hero-copy"><span>ARCHIVO · CONTROL FÍSICO Y DIGITAL</span><h2>Todo lo organizado, ubicado y listo para conservar.</h2><p>Carpetas, cajas, transferencias y tiempos de retención se consultan desde un solo centro. La clasificación TRD ya viene heredada del expediente.</p><div className="module-hero-actions"><Link className="ui-btn yellow" href="/archivo/transferir">Nueva transferencia</Link><Link className="ui-btn secondary" href="/trabajo/organizar">Organizar documentación</Link></div></div><div className="module-hero-visual"><div className="module-orbit"><b>AR</b><small>ARCHIVO</small></div></div></section>
   <div className="module-kpis"><article className="module-kpi"><div className="module-kpi-head"><small>Carpetas</small><span className="module-kpi-icon"><Icon name="folder"/></span></div><strong>{counts.folders}</strong><p>unidades físicas o digitales organizadas</p></article><article className="module-kpi"><div className="module-kpi-head"><small>Cajas</small><span className="module-kpi-icon"><Icon name="box"/></span></div><strong>{counts.boxes}</strong><p>contenedores registrados en el archivo</p></article><article className="module-kpi accent"><div className="module-kpi-head"><small>Transferencias</small><span className="module-kpi-icon"><Icon name="transfer"/></span></div><strong>{counts.transfers}</strong><p>movimientos documentales trazables</p></article><article className="module-kpi"><div className="module-kpi-head"><small>Retención</small><span className="module-kpi-icon"><Icon name="clock"/></span></div><strong>{counts.retention}</strong><p>expedientes con fechas de conservación</p></article></div>
   <div className="archive-health"><div className="archive-flow"><span>CICLO DE CONSERVACIÓN</span><h3>Cómo está distribuido el archivo</h3><div className="archive-flow-track"><div className="archive-flow-step"><b>{phaseCounts.management}</b><small>Cajas en archivo de gestión</small></div><div className="archive-flow-step"><b>{phaseCounts.central}</b><small>Cajas en archivo central</small></div><div className="archive-flow-step"><b>{phaseCounts.historical}</b><small>Cajas en histórico</small></div></div></div><div className="archive-alerts"><span>CALIDAD DEL ARCHIVO</span><h3>Elementos por completar</h3><div className="archive-alert-item"><b>Carpetas sin caja</b><strong>{counts.unboxed}</strong></div><div className="archive-alert-item"><b>Cajas sin ubicación</b><strong>{counts.unlocated}</strong></div><div className="archive-alert-item"><b>Transferencias registradas</b><strong>{counts.transfers}</strong></div></div></div>
   <div className="module-toolbar"><div className="ui-tabs"><button className={view==="folders"?"active":""} onClick={()=>setView("folders")}>Carpetas</button><button className={view==="boxes"?"active":""} onClick={()=>setView("boxes")}>Cajas</button><button className={view==="transfers"?"active":""} onClick={()=>setView("transfers")}>Transferencias</button><button className={view==="retention"?"active":""} onClick={()=>setView("retention")}>Retención</button></div><input className="module-search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por código, dependencia, caja, TRD…"/></div>
   <section className="module-panel"><div className="module-panel-head"><div><span>VISTA ACTUAL</span><h3>{title}</h3><p>{desc}</p></div>{view==="transfers"&&<Link href="/archivo/transferir" className="ui-btn yellow">Nueva transferencia</Link>}</div><div className="module-table-wrap">
    {view==="folders"&&(filter(folders).length?<table className="ui-table"><thead><tr><th>Carpeta</th><th>Expediente</th><th>Dependencia / TRD</th><th>Caja</th><th>Folios</th></tr></thead><tbody>{filter(folders).map(x=><tr key={x.id}><td><b>{x.folder_number||"Sin número"}</b><br/><small>{x.inventory_code||"Sin inventario"}</small></td><td><b>{x.expedientes?.title||"Sin expediente"}</b><br/><small>{x.expedientes?.expediente_code}</small></td><td>{x.expedientes?.organizational_units?.name||"—"}<br/><small>{x.expedientes?.trd_entries?.name||"Sin TRD"}</small></td><td>{x.archive_boxes?.box_number||"Sin asignar"}<br/><small>{x.archive_boxes?.phase||""}</small></td><td>{x.initial_folio||"—"} – {x.final_folio||"—"}</td></tr>)}</tbody></table>:<div className="module-empty"><div><span className="module-empty-icon"><Icon name="folder"/></span><b>No hay carpetas para mostrar</b><span>Cuando organices expedientes, sus carpetas aparecerán aquí con caja, folios y clasificación heredada.</span></div></div>)}
    {view==="boxes"&&(filter(boxes).length?<table className="ui-table"><thead><tr><th>Caja</th><th>Fase</th><th>Ubicación</th><th>Estado</th><th>Identificación</th></tr></thead><tbody>{filter(boxes).map(x=><tr key={x.id}><td><b>{x.box_number}</b></td><td><span className="ui-pill">{x.phase}</span></td><td>{x.physical_locations?.name||"Por ubicar"}<br/><small>{x.physical_locations?.code||""}</small></td><td>{x.status}</td><td>{x.barcode||x.qr_code||"—"}</td></tr>)}</tbody></table>:<div className="module-empty"><div><span className="module-empty-icon"><Icon name="box"/></span><b>No hay cajas registradas</b><span>Las cajas se crean desde Organización y luego pueden transferirse entre fases documentales.</span></div></div>)}
    {view==="transfers"&&(filter(transfers).length?<table className="ui-table"><thead><tr><th>Número</th><th>Tipo</th><th>Dependencia</th><th>Fecha</th><th>Ruta</th><th>Estado</th></tr></thead><tbody>{filter(transfers).map(x=><tr key={x.id}><td><b>{x.transfer_number}</b></td><td>{x.transfer_type}</td><td>{x.organizational_units?.name||"—"}</td><td>{date(x.transfer_date)}</td><td>{x.from_phase} → {x.to_phase}</td><td><span className="ui-pill yellow">{x.status}</span></td></tr>)}</tbody></table>:<div className="module-empty"><div><span className="module-empty-icon"><Icon name="transfer"/></span><b>No hay transferencias registradas</b><span>Prepara la primera transferencia cuando existan expedientes organizados y asignados a caja.</span></div></div>)}
    {view==="retention"&&(filter(retention).length?<table className="ui-table"><thead><tr><th>Expediente</th><th>TRD</th><th>Gestión hasta</th><th>Central hasta</th><th>Disposición</th></tr></thead><tbody>{filter(retention).map(x=><tr key={x.id}><td><b>{x.title}</b><br/><small>{x.expediente_code}</small></td><td>{x.trd_entries?.name||"—"}</td><td>{date(x.retention_management_due)}</td><td>{date(x.retention_central_due)}</td><td>{x.disposition}<br/><small>{date(x.disposition_due)}</small></td></tr>)}</tbody></table>:<div className="module-empty"><div><span className="module-empty-icon"><Icon name="clock"/></span><b>Sin fechas de retención calculadas</b><span>Las fechas aparecerán cuando los expedientes tengan cierre y reglas TRD suficientes para calcular conservación.</span></div></div>)}
   </div></section>
  </div>
 </UnifiedShell>
}
