"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import UnifiedShell from "@/components/UnifiedShell";
import { supabase } from "@/lib/supabase";

type Row=Record<string,any>; type View="folders"|"boxes"|"transfers"|"retention";
const date=(v:any)=>v?new Intl.DateTimeFormat("es-CO",{dateStyle:"medium"}).format(new Date(v)):"—";

export default function ArchiveCenter(){
 const [view,setView]=useState<View>("folders"); const [folders,setFolders]=useState<Row[]>([]); const [boxes,setBoxes]=useState<Row[]>([]); const [transfers,setTransfers]=useState<Row[]>([]); const [retention,setRetention]=useState<Row[]>([]); const [q,setQ]=useState("");
 useEffect(()=>{(async()=>{const v=new URLSearchParams(window.location.search).get("vista"); if(v==="transferencias")setView("transfers");const [f,b,t,r]=await Promise.all([supabase.from("archive_folders").select("*,archive_boxes(box_number,phase),expedientes(id,expediente_code,title,status,organizational_units(name),trd_entries(name))").order("created_at",{ascending:false}).limit(500),supabase.from("archive_boxes").select("*,physical_locations(name,code)").order("created_at",{ascending:false}).limit(400),supabase.from("transfers").select("*,organizational_units(name)").order("transfer_date",{ascending:false}).limit(400),supabase.from("expedientes").select("id,expediente_code,title,status,phase,retention_management_due,retention_central_due,disposition_due,disposition,organizational_units(name),trd_entries(name)").or("retention_management_due.not.is.null,retention_central_due.not.is.null,disposition_due.not.is.null").order("retention_management_due",{ascending:true,nullsFirst:false}).limit(500)]);setFolders(f.data||[]);setBoxes(b.data||[]);setTransfers(t.data||[]);setRetention(r.data||[]);})()},[]);
 const filter=(rows:Row[])=>{const s=q.trim().toLowerCase();return !s?rows:rows.filter(x=>JSON.stringify(x).toLowerCase().includes(s))};
 const counts=useMemo(()=>({folders:folders.length,boxes:boxes.length,transfers:transfers.length,retention:retention.length}),[folders,boxes,transfers,retention]);
 return <UnifiedShell eyebrow="ARCHIVO" title="Archivo y conservación" actions={<Link className="ui-btn yellow" href="/trabajo/organizar">Organizar expediente</Link>}>
  <div className="ui-page-head"><div><span>ARCHIVO</span><h2>Ubica, mueve y conserva</h2><p>Una sola vista para la documentación ya organizada. Aquí no se vuelve a clasificar ni a diligenciar la TRD.</p></div></div>
  <div className="ui-grid cols-4"><div className="ui-card ui-metric"><small>Carpetas</small><b>{counts.folders}</b><span>unidades físicas/digitales</span></div><div className="ui-card ui-metric"><small>Cajas</small><b>{counts.boxes}</b><span>gestión, central e histórico</span></div><div className="ui-card ui-metric"><small>Transferencias</small><b>{counts.transfers}</b><span>movimientos registrados</span></div><div className="ui-card ui-metric"><small>Retención</small><b>{counts.retention}</b><span>expedientes con fechas calculadas</span></div></div>
  <section className="ui-section"><div className="ui-section-head"><div className="ui-tabs"><button className={view==="folders"?"active":""} onClick={()=>setView("folders")}>Carpetas</button><button className={view==="boxes"?"active":""} onClick={()=>setView("boxes")}>Cajas</button><button className={view==="transfers"?"active":""} onClick={()=>setView("transfers")}>Transferencias</button><button className={view==="retention"?"active":""} onClick={()=>setView("retention")}>Retención</button></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar…" style={{height:38,border:"1px solid var(--ui-line)",borderRadius:11,padding:"0 11px",font:"inherit",fontSize:8.5,minWidth:230}}/></div>
   <div className="ui-card" style={{overflow:"hidden"}}>
    {view==="folders"&&<table className="ui-table"><thead><tr><th>Carpeta</th><th>Expediente</th><th>Dependencia / TRD</th><th>Caja</th><th>Folios</th></tr></thead><tbody>{filter(folders).map(x=><tr key={x.id}><td><b>{x.folder_number||"Sin número"}</b><br/><small>{x.inventory_code||"Sin inventario"}</small></td><td>{x.expedientes?.title}<br/><small>{x.expedientes?.expediente_code}</small></td><td>{x.expedientes?.organizational_units?.name}<br/><small>{x.expedientes?.trd_entries?.name}</small></td><td>{x.archive_boxes?.box_number||"Sin asignar"}<br/><small>{x.archive_boxes?.phase||""}</small></td><td>{x.initial_folio||"—"} – {x.final_folio||"—"}</td></tr>)}</tbody></table>}
    {view==="boxes"&&<table className="ui-table"><thead><tr><th>Caja</th><th>Fase</th><th>Ubicación</th><th>Estado</th><th>Identificación</th></tr></thead><tbody>{filter(boxes).map(x=><tr key={x.id}><td><b>{x.box_number}</b></td><td><span className="ui-pill">{x.phase}</span></td><td>{x.physical_locations?.name||"Por ubicar"}<br/><small>{x.physical_locations?.code||""}</small></td><td>{x.status}</td><td>{x.barcode||x.qr_code||"—"}</td></tr>)}</tbody></table>}
    {view==="transfers"&&<>{<div style={{padding:14,display:"flex",justifyContent:"flex-end",borderBottom:"1px solid var(--ui-line)"}}><Link href="/archivo/transferir" className="ui-btn yellow">Nueva transferencia</Link></div>}<table className="ui-table"><thead><tr><th>Número</th><th>Tipo</th><th>Dependencia</th><th>Fecha</th><th>Ruta</th><th>Estado</th></tr></thead><tbody>{filter(transfers).map(x=><tr key={x.id}><td><b>{x.transfer_number}</b></td><td>{x.transfer_type}</td><td>{x.organizational_units?.name||"—"}</td><td>{date(x.transfer_date)}</td><td>{x.from_phase} → {x.to_phase}</td><td><span className="ui-pill yellow">{x.status}</span></td></tr>)}</tbody></table></>}
    {view==="retention"&&<table className="ui-table"><thead><tr><th>Expediente</th><th>TRD</th><th>Gestión hasta</th><th>Central hasta</th><th>Disposición</th></tr></thead><tbody>{filter(retention).map(x=><tr key={x.id}><td><b>{x.title}</b><br/><small>{x.expediente_code}</small></td><td>{x.trd_entries?.name||"—"}</td><td>{date(x.retention_management_due)}</td><td>{date(x.retention_central_due)}</td><td>{x.disposition}<br/><small>{date(x.disposition_due)}</small></td></tr>)}</tbody></table>}
   </div>
  </section>
 </UnifiedShell>
}
