"use client";

import { useEffect, useMemo, useState } from "react";
import UnifiedShell from "@/components/UnifiedShell";
import { supabase } from "@/lib/supabase";

type Row=Record<string,any>;

export default function CleanTrdCenter(){
 const [rows,setRows]=useState<Row[]>([]);const [office,setOffice]=useState("");const [q,setQ]=useState("");const [selected,setSelected]=useState<Row|null>(null);
 useEffect(()=>{(async()=>{const {data}=await supabase.from("trd_canonical_catalog").select("*").limit(1000);const r=data||[];setRows(r);setOffice(r[0]?.office_name||"");setSelected(r[0]||null)})()},[]);
 const offices=useMemo(()=>[...new Set(rows.map(x=>x.office_name).filter(Boolean))].sort(),[rows]);
 const visible=useMemo(()=>{const s=q.trim().toLowerCase();return rows.filter(x=>(!office||x.office_name===office)&&(!s||`${x.series_name} ${x.subseries_name||""} ${x.document_type_name||""} ${x.canonical_code||""}`.toLowerCase().includes(s)))},[rows,office,q]);
 const series=useMemo(()=>{const map=new Map<string,Row>();visible.forEach(x=>{if(x.series_id&&!map.has(x.series_id))map.set(x.series_id,x)});return [...map.values()]},[visible]);
 const stats=useMemo(()=>{const seriesIds=new Set(rows.map(x=>x.series_id).filter(Boolean));const subIds=new Set(rows.map(x=>x.subseries_id).filter(Boolean));const typeIds=new Set(rows.map(x=>x.document_type_id).filter(Boolean));return{series:seriesIds.size,subs:subIds.size,types:typeIds.size,valuation:rows.filter(x=>x.requires_valuation).length}},[rows]);
 function childrenSeries(id:string){const subs=new Map<string,Row>();visible.filter(x=>x.series_id===id&&x.subseries_id).forEach(x=>{if(!subs.has(x.subseries_id))subs.set(x.subseries_id,x)});const direct=visible.filter(x=>x.series_id===id&&!x.subseries_id&&x.document_type_id);return{subs:[...subs.values()],direct}}
 function types(seriesId:string,subId?:string){return visible.filter(x=>x.series_id===seriesId&&x.document_type_id&&(subId?x.subseries_id===subId:!x.subseries_id))}
 const name=(x:Row|null)=>x?.document_type_name||x?.subseries_name||x?.series_name||x?.canonical_name||"Clasificación TRD";
 return <UnifiedShell eyebrow="CONFIGURACIÓN · TRD" title="Tabla de Retención Documental">
  <div className="module-stack">
   <section className="module-hero"><div className="module-hero-copy"><span>FUENTE ÚNICA DE CLASIFICACIÓN</span><h2>La estructura documental que gobierna todo el SGDEA.</h2><p>Explora dependencia, serie, subserie y tipo documental con retención y disposición visibles. Los expedientes heredan estas reglas y los formatos reutilizan la misma clasificación.</p></div><div className="module-hero-visual"><div className="module-orbit"><b>TRD</b><small>CLASIFICACIÓN</small></div></div></section>
   <div className="trd-stats"><div className="trd-stat"><small>Series</small><b>{stats.series}</b></div><div className="trd-stat"><small>Subseries</small><b>{stats.subs}</b></div><div className="trd-stat"><small>Tipos documentales</small><b>{stats.types}</b></div><div className="trd-stat"><small>Requieren valoración</small><b>{stats.valuation}</b></div></div>
   <div className="module-toolbar"><label className="ui-field" style={{minWidth:260}}><span>Dependencia</span><select value={office} onChange={e=>{setOffice(e.target.value);setSelected(null)}}>{offices.map(x=><option key={x}>{x}</option>)}</select></label><label className="ui-field" style={{flex:1,minWidth:280}}><span>Buscar en la TRD</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Serie, subserie, tipo documental o código"/></label></div>
   <div className="trd-browser"><section className="trd-tree"><div className="trd-tree-head"><div><small>ESTRUCTURA</small><b>{office||"Selecciona una dependencia"}</b></div><span className="ui-pill">{visible.length} registros</span></div><div className="trd-tree-scroll">{series.length?series.map(s=>{const ch=childrenSeries(s.series_id);return <details key={s.series_id} open={!!q} className="trd-series"><summary onClick={()=>setSelected(s)}><span className="trd-node-badge">S</span><span className="trd-node-copy"><b>{s.series_name}</b><small>{s.series_code||s.canonical_code||"Sin código"}</small></span><span className="ui-pill">{ch.subs.length+ch.direct.length}</span></summary><div className="trd-children">{ch.subs.map(sub=><details key={sub.subseries_id} open={!!q} className="trd-subseries"><summary onClick={()=>setSelected(sub)}><span className="trd-node-badge sub">SS</span><span className="trd-node-copy"><b>{sub.subseries_name}</b><small>{sub.canonical_code||"Subserie"}</small></span><small style={{fontSize:8,color:"#8092a2"}}>{types(s.series_id,sub.subseries_id).length} tipos</small></summary><div className="trd-types">{types(s.series_id,sub.subseries_id).map(t=><button key={t.document_type_id} onClick={()=>setSelected(t)} className="trd-type-btn">{t.document_type_name}</button>)}</div></details>)}{ch.direct.map(t=><button key={t.document_type_id} onClick={()=>setSelected(t)} className="trd-type-btn">{t.document_type_name}</button>)}</div></details>}):<div className="module-empty"><div><span className="module-empty-icon">TRD</span><b>No hay coincidencias</b><span>Cambia la dependencia o ajusta el término de búsqueda para explorar la estructura.</span></div></div>}</div></section>
    <aside className="trd-detail">{selected?<><div className="ui-section-head"><div><span>DETALLE DE CLASIFICACIÓN</span><h3>{name(selected)}</h3></div><span className={`ui-pill ${selected.requires_valuation?"yellow":"green"}`}>{selected.level||"TRD"}</span></div><div className="ui-divider"/><div className="ui-context"><span>Dependencia</span><b>{selected.office_name||office||"—"}</b></div><div style={{height:8}}/><div className="ui-context"><span>Serie</span><b>{selected.series_name||"—"}</b></div>{selected.subseries_name&&<><div style={{height:8}}/><div className="ui-context"><span>Subserie</span><b>{selected.subseries_name}</b></div></>}{selected.document_type_name&&<><div style={{height:8}}/><div className="ui-context"><span>Tipo documental</span><b>{selected.document_type_name}</b></div></>}<div className="ui-divider"/><div className="ui-grid cols-2"><div className="ui-context"><span>Gestión</span><b>{selected.retention_management_raw||"—"}</b></div><div className="ui-context"><span>Central</span><b>{selected.retention_central_raw||"—"}</b></div></div><div style={{height:8}}/><div className="ui-context"><span>Disposición</span><b>{selected.disposition||"Pendiente"}</b></div><div style={{height:8}}/><div className="ui-context"><span>Código</span><b>{selected.canonical_code||"—"}</b></div><div className={`ui-callout ${selected.requires_valuation?"warn":"ok"}`} style={{marginTop:12}}>{selected.requires_valuation?"Este registro requiere valoración documental antes de consolidar su disposición.":"Registro disponible para clasificación operativa."}</div><div className="ui-divider"/><small style={{fontSize:8,color:"#8faabe"}}>Versión: {selected.trd_version_code||"—"} · Estado: {selected.trd_version_status||"—"}</small></>:<div className="module-empty" style={{background:"transparent",minHeight:300}}><div><span className="module-empty-icon">TRD</span><b style={{color:"#fff"}}>Selecciona una clasificación</b><span style={{color:"#91aabd"}}>Verás aquí retención, disposición, código y jerarquía documental.</span></div></div>}</aside>
   </div>
  </div>
 </UnifiedShell>
}
