"use client";

import { ReactNode, useEffect, useMemo, useState } from "react";
import UnifiedShell from "@/components/UnifiedShell";
import { supabase } from "@/lib/supabase";

type Row=Record<string,any>; type View="tasks"|"approvals"|"audit";
const dt=(v:any)=>v?new Intl.DateTimeFormat("es-CO",{dateStyle:"short",timeStyle:"short"}).format(new Date(v)):"—";
function Icon({name}:{name:"task"|"approve"|"audit"|"pulse"}){const p:Record<string,ReactNode>={task:<><rect x="5" y="4" width="14" height="16" rx="2"/><path d="M8 9h8M8 13h5M8 17h4"/></>,approve:<><circle cx="12" cy="12" r="8.5"/><path d="m8.5 12 2.2 2.2 4.8-5"/></>,audit:<><path d="M6 4h12v16H6z"/><path d="M9 8h6M9 12h6M9 16h4"/></>,pulse:<><path d="M3 12h4l2-5 4 10 2-5h6"/></>};return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{p[name]}</svg>}

export default function ControlCenter(){
 const [view,setView]=useState<View>("tasks");const [tasks,setTasks]=useState<Row[]>([]);const [approvals,setApprovals]=useState<Row[]>([]);const [audit,setAudit]=useState<Row[]>([]);const [q,setQ]=useState("");
 useEffect(()=>{(async()=>{const [t,a,l]=await Promise.all([supabase.from("workflow_tasks").select("*").order("created_at",{ascending:false}).limit(400),supabase.from("approval_requests").select("*").order("created_at",{ascending:false}).limit(400),supabase.from("audit_logs").select("*").order("occurred_at",{ascending:false}).limit(500)]);setTasks(t.data||[]);setApprovals(a.data||[]);setAudit(l.data||[])})()},[]);
 const open=tasks.filter(x=>x.status!=="completed").length;const completed=tasks.filter(x=>x.status==="completed").length;const pending=approvals.filter(x=>["pending","draft"].includes(x.status)).length;const approved=approvals.filter(x=>x.status==="approved").length;
 const filtered=useMemo(()=>{const s=q.trim().toLowerCase();const list=view==="tasks"?tasks:view==="approvals"?approvals:audit;return !s?list:list.filter(x=>JSON.stringify(x).toLowerCase().includes(s))},[q,view,tasks,approvals,audit]);
 const title={tasks:"Tareas y pendientes",approvals:"Solicitudes de aprobación",audit:"Evidencia de auditoría"}[view];
 const desc={tasks:"Prioriza lo que aún necesita gestión y consulta sus vencimientos.",approvals:"Revisa solicitudes que requieren decisión o seguimiento.",audit:"Consulta la trazabilidad de acciones realizadas dentro del SGDEA."}[view];
 return <UnifiedShell eyebrow="CONTROL" title="Seguimiento y trazabilidad">
  <div className="module-stack">
   <section className="module-hero"><div className="module-hero-copy"><span>CONTROL · SUPERVISIÓN</span><h2>Lo importante aparece antes de convertirse en problema.</h2><p>Pendientes, aprobaciones y auditoría se concentran en una sola vista para facilitar seguimiento, priorización y trazabilidad.</p></div><div className="module-hero-visual"><div className="module-orbit"><b>CT</b><small>CONTROL</small></div></div></section>
   <div className="module-kpis"><article className="module-kpi accent"><div className="module-kpi-head"><small>Tareas abiertas</small><span className="module-kpi-icon"><Icon name="task"/></span></div><strong>{open}</strong><p>actividades que todavía requieren gestión</p></article><article className="module-kpi"><div className="module-kpi-head"><small>Aprobaciones pendientes</small><span className="module-kpi-icon"><Icon name="approve"/></span></div><strong>{pending}</strong><p>solicitudes esperando revisión o decisión</p></article><article className="module-kpi"><div className="module-kpi-head"><small>Completadas / aprobadas</small><span className="module-kpi-icon"><Icon name="pulse"/></span></div><strong>{completed+approved}</strong><p>gestiones resueltas dentro del flujo</p></article><article className="module-kpi"><div className="module-kpi-head"><small>Eventos auditados</small><span className="module-kpi-icon"><Icon name="audit"/></span></div><strong>{audit.length}</strong><p>últimos eventos cargados para trazabilidad</p></article></div>
   <div className="control-focus"><div className="control-queue"><span>PULSO OPERATIVO</span><h3>{open||pending?"Hay elementos que merecen atención":"La operación está al día"}</h3><p>{open||pending?`Actualmente hay ${open} tareas abiertas y ${pending} aprobaciones pendientes. Usa las vistas inferiores para entrar al detalle.`:"No hay pendientes relevantes en las colas cargadas. La auditoría sigue disponible para consulta."}</p><div className="control-pulse"><i style={{"--fill":`${Math.min(100,open*12)}%`} as any}/><i style={{"--fill":`${Math.min(100,pending*16)}%`} as any}/><i style={{"--fill":`${Math.min(100,(completed+approved)*8)}%`} as any}/></div></div><div className="control-legend"><h3>Cómo leer el control</h3><div className="control-legend-row"><span className="control-dot"/> Amarillo: requiere atención o decisión.</div><div className="control-legend-row"><span className="control-dot green"/> Verde: gestión completada o aprobada.</div><div className="control-legend-row"><span className="control-dot blue"/> Azul: evidencia y trazabilidad del sistema.</div></div></div>
   <div className="module-toolbar"><div className="ui-tabs"><button className={view==="tasks"?"active":""} onClick={()=>setView("tasks")}>Pendientes</button><button className={view==="approvals"?"active":""} onClick={()=>setView("approvals")}>Aprobaciones</button><button className={view==="audit"?"active":""} onClick={()=>setView("audit")}>Auditoría</button></div><input className="module-search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar en la vista actual…"/></div>
   <section className="module-panel"><div className="module-panel-head"><div><span>SEGUIMIENTO</span><h3>{title}</h3><p>{desc}</p></div><span className="ui-pill">{filtered.length} registros</span></div>
    {view==="tasks"&&(filtered.length?<div className="ui-list">{filtered.map(x=><div className="ui-list-row" key={x.id}><span className="ui-list-main"><b>{x.title}</b><small>{x.description||x.entity_type||"Tarea documental"}</small></span><span className="ui-list-meta"><span className={`ui-pill ${x.status==="completed"?"green":"yellow"}`}>{x.status}</span><small>{x.due_at?`Vence ${dt(x.due_at)}`:`Prioridad ${x.priority||"normal"}`}</small></span></div>)}</div>:<div className="module-empty"><div><span className="module-empty-icon"><Icon name="task"/></span><b>No hay tareas en esta vista</b><span>Cuando un proceso genere un pendiente, aparecerá aquí con su estado, prioridad y fecha límite.</span></div></div>)}
    {view==="approvals"&&(filtered.length?<div className="ui-list">{filtered.map(x=><div className="ui-list-row" key={x.id}><span className="ui-list-main"><b>{x.title}</b><small>{x.entity_type||"Solicitud"} · creado {dt(x.created_at)}</small></span><span className="ui-list-meta"><span className={`ui-pill ${x.status==="approved"?"green":"yellow"}`}>{x.status}</span><small>{x.due_at?`Vence ${dt(x.due_at)}`:"Sin fecha límite"}</small></span></div>)}</div>:<div className="module-empty"><div><span className="module-empty-icon"><Icon name="approve"/></span><b>No hay aprobaciones registradas</b><span>Las solicitudes de aprobación aparecerán aquí para facilitar su seguimiento.</span></div></div>)}
    {view==="audit"&&(filtered.length?<div className="module-table-wrap"><table className="ui-table"><thead><tr><th>Fecha</th><th>Acción</th><th>Entidad</th><th>Usuario</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td>{dt(x.occurred_at)}</td><td><b>{x.action}</b></td><td>{x.entity_type}<br/><small>{x.entity_id}</small></td><td>{x.actor_email||x.actor_id||"Sistema"}</td></tr>)}</tbody></table></div>:<div className="module-empty"><div><span className="module-empty-icon"><Icon name="audit"/></span><b>Sin eventos para mostrar</b><span>La auditoría se alimenta automáticamente con las acciones trazables del sistema.</span></div></div>)}
   </section>
  </div>
 </UnifiedShell>
}
