"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import UnifiedShell from "@/components/UnifiedShell";
import { supabase } from "@/lib/supabase";

type Row=Record<string,any>;

export default function SettingsCenter(){
 const [version,setVersion]=useState<Row|null>(null);const [offices,setOffices]=useState<Row[]>([]);const [users,setUsers]=useState<Row[]>([]);
 useEffect(()=>{(async()=>{const [v,o,u]=await Promise.all([supabase.from("trd_versions").select("*").order("created_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("organizational_units").select("id,name,code,active").order("name"),supabase.from("profiles").select("id,full_name,email,role,active,organizational_units(name)").order("full_name").limit(300)]);setVersion(v.data||null);setOffices(o.data||[]);setUsers(u.data||[])})()},[]);
 const stats=useMemo(()=>({activeOffices:offices.filter(x=>x.active).length,activeUsers:users.filter(x=>x.active).length,admins:users.filter(x=>["super_admin","records_admin","office_admin"].includes(x.role)).length}),[offices,users]);
 return <UnifiedShell eyebrow="CONFIGURACIÓN" title="Normativa y administración">
  <div className="module-stack">
   <section className="module-hero"><div className="module-hero-copy"><span>GOBIERNO DEL SGDEA</span><h2>Las reglas del sistema, claras y bajo control.</h2><p>Administra la estructura documental, las dependencias y los accesos desde un centro separado del trabajo operativo diario.</p></div><div className="module-hero-visual"><div className="module-orbit"><b>CFG</b><small>GOBIERNO</small></div></div></section>
   <div className="module-status-grid"><div className="module-status"><span className="module-status-icon">TRD</span><div><b>{version?.version_code||"—"}</b><small>versión documental actualmente cargada</small></div></div><div className="module-status"><span className="module-status-icon">ORG</span><div><b>{stats.activeOffices}</b><small>dependencias activas para clasificación y asignación</small></div></div><div className="module-status"><span className="module-status-icon">USR</span><div><b>{stats.activeUsers}</b><small>usuarios con acceso habilitado al SGDEA</small></div></div></div>
   <div className="settings-grid"><Link href="/trd" className="settings-card"><span className="settings-card-icon">TRD</span><h3>Tabla de Retención Documental</h3><p>Consulta la estructura de series, subseries y tipos documentales que gobierna expedientes, retención y disposición.</p><footer><span>{version?.status||"Sin estado"}</span><b>Explorar TRD →</b></footer></Link><div className="settings-card"><span className="settings-card-icon">ORG</span><h3>Dependencias</h3><p>Visualiza la estructura organizacional que participa en la producción, clasificación y responsabilidad documental.</p><footer><span>{offices.length} registradas</span><b>{stats.activeOffices} activas</b></footer></div><Link href="/configuracion/usuarios" className="settings-card"><span className="settings-card-icon">USR</span><h3>Usuarios y permisos</h3><p>Consulta perfiles, roles, estado de acceso y dependencia asignada para cada usuario del sistema.</p><footer><span>{stats.admins} administradores</span><b>Gestionar accesos →</b></footer></Link></div>
   <section className="module-panel"><div className="module-panel-head"><div><span>FUENTE DE VERDAD</span><h3>Estado de gobierno documental</h3><p>Resumen de la configuración que condiciona el comportamiento del SGDEA.</p></div><span className={`ui-pill ${version?.status==="approved"?"green":"yellow"}`}>{version?.status||"Sin estado"}</span></div><div style={{padding:20}}><div className="ui-grid cols-2"><div className="ui-context"><span>TRD actual</span><b>{version?.title||"Sin versión cargada"}</b><small>{version?.version_code||"—"}</small></div><div className="ui-context"><span>Accesos administrativos</span><b>{stats.admins} perfiles</b><small>super, documental y dependencia</small></div></div><div className="ui-callout info" style={{marginTop:14}}>La TRD debe seguir siendo la fuente única de clasificación. Los formularios operativos heredan la información seleccionada en el expediente y no deben crear clasificaciones paralelas.</div></div></section>
   <section className="module-panel"><div className="module-panel-head"><div><span>ESTRUCTURA ORGANIZACIONAL</span><h3>Dependencias activas</h3><p>Primeras unidades disponibles para los procesos documentales.</p></div><span className="ui-pill">{stats.activeOffices} activas</span></div><div className="ui-list">{offices.slice(0,12).map(x=><div className="ui-list-row" key={x.id}><span className="ui-list-main"><b>{x.name}</b><small>{x.code||"Sin código"}</small></span><span className="ui-list-meta"><span className={`ui-pill ${x.active?"green":""}`}>{x.active?"Activa":"Inactiva"}</span></span></div>)}</div></section>
  </div>
 </UnifiedShell>
}
