"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import UnifiedShell from "@/components/UnifiedShell";
import { supabase } from "@/lib/supabase";
import type { Profile } from "@/lib/types";

type Row=Record<string,any>;
const today=()=>new Date().toISOString().slice(0,10);

export default function TransferFlow(){
 const [profile,setProfile]=useState<Profile|null>(null);const [exps,setExps]=useState<Row[]>([]);const [selected,setSelected]=useState<string[]>([]);const [type,setType]=useState("primary");const [q,setQ]=useState("");const [saving,setSaving]=useState(false);const [done,setDone]=useState<Row|null>(null);const [notice,setNotice]=useState("");
 useEffect(()=>{(async()=>{const {data:s}=await supabase.auth.getSession();if(!s.session)return;const {data:p}=await supabase.from("profiles").select("*").eq("id",s.session.user.id).maybeSingle();setProfile(p as Profile);const {data}=await supabase.from("expedientes").select("id,office_id,trd_entry_id,expediente_code,title,status,phase,metadata,organizational_units(name),trd_entries(id,trd_version_id,name),archive_folders(id,folder_number,box_id,archive_boxes(id,box_number,phase))").order("updated_at",{ascending:false}).limit(700);setExps(data||[])})()},[]);
 const candidates=useMemo(()=>exps.filter(x=>{const hasBox=(x.archive_folders||[]).some((f:any)=>f.box_id);const phaseOk=type==="primary"?x.phase==="management":x.phase==="central";const s=`${x.expediente_code} ${x.title} ${x.organizational_units?.name}`.toLowerCase();return hasBox&&phaseOk&&(!q.trim()||s.includes(q.toLowerCase()))}),[exps,type,q]);
 function toggle(id:string){setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile?.organization_id||!selected.length)return setNotice("Selecciona al menos un expediente organizado.");setSaving(true);const f=new FormData(e.currentTarget);const chosen=exps.filter(x=>selected.includes(x.id));const versions=[...new Set(chosen.map(x=>x.trd_entries?.trd_version_id).filter(Boolean))];if(versions.length>1){setSaving(false);return setNotice("Los expedientes seleccionados pertenecen a versiones TRD diferentes.")}const number=`TR-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`;const payload={organization_id:profile.organization_id,transfer_number:number,transfer_type:type,from_phase:type==="primary"?"management":"central",to_phase:type==="primary"?"central":"historical",office_id:f.get("office_id")||profile.office_id||null,transfer_date:f.get("transfer_date")||today(),status:"draft",object:f.get("object")||null,delivered_by:profile.id,trd_version_id:versions[0]||null,metadata:{delivered_name:profile.full_name||profile.email,received_name:f.get("received_name")||null,notes:f.get("notes")||null}};const ins=await supabase.from("transfers").insert(payload).select("*").single();if(ins.error){setSaving(false);return setNotice(ins.error.message)}const items=chosen.map(x=>{const folder=(x.archive_folders||[]).find((ff:any)=>ff.box_id);return{transfer_id:ins.data.id,expediente_id:x.id,box_id:folder?.box_id||null,observations:null}});const ii=await supabase.from("transfer_items").insert(items);setSaving(false);if(ii.error)return setNotice(ii.error.message);setDone({...ins.data,chosen});setNotice(`Transferencia ${number} creada. El D-FT-27 ya puede imprimirse.`)}
 function print(){if(!done)return;const w=window.open("","_blank","width=1000,height=760");if(!w)return;const rows=(done.chosen||[]).map((x:Row,i:number)=>`<tr><td>${i+1}</td><td>${x.expediente_code}</td><td>${x.title}</td><td>${x.organizational_units?.name||""}</td><td>${x.trd_entries?.name||""}</td><td>${x.archive_folders?.[0]?.archive_boxes?.box_number||""}</td></tr>`).join("");w.document.write(`<!doctype html><html><head><title>D-FT-27</title><style>body{font-family:Arial;padding:28px;color:#111}.head{display:flex;justify-content:space-between;border-bottom:3px solid #f5c518;padding-bottom:12px}.brand{font-size:20px;font-weight:800}table{width:100%;border-collapse:collapse;margin-top:18px}th,td{border:1px solid #999;padding:7px;font-size:10px}th{background:#071b33;color:#fff}.meta{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:16px;font-size:11px}@media print{button{display:none}}</style></head><body><div class="head"><div><div class="brand">ELECTROINGENIERÍA S.A.S.</div><small>SGDEA</small></div><b>D-FT-27 · TRANSFERENCIA DOCUMENTAL</b></div><div class="meta"><div><b>Número:</b> ${done.transfer_number}</div><div><b>Fecha:</b> ${done.transfer_date}</div><div><b>Tipo:</b> ${done.transfer_type}</div><div><b>Ruta:</b> ${done.from_phase} → ${done.to_phase}</div></div><table><thead><tr><th>#</th><th>Expediente</th><th>Asunto</th><th>Dependencia</th><th>TRD</th><th>Caja</th></tr></thead><tbody>${rows}</tbody></table><br><button onclick="window.print()">Imprimir</button></body></html>`);w.document.close()}
 return <UnifiedShell eyebrow="ARCHIVO · TRANSFERENCIA" title="Preparar transferencia" actions={<Link className="ui-btn secondary" href="/archivo?vista=transferencias">← Archivo</Link>}>
  <div className="ui-page-head"><div><span>D-FT-27</span><h2>Transferir documentación organizada</h2><p>El formato se construye desde expedientes y cajas existentes. No se vuelve a escribir su clasificación.</p></div></div>{notice&&<div className={`ui-callout ${done?"ok":"warn"}`} style={{marginBottom:12}}>{notice}</div>}
  <div className="ui-two-pane"><section className="ui-card pad"><div className="ui-section-head"><div><span>PASO 1</span><h3>Seleccionar expedientes</h3></div><span className="ui-pill yellow">{selected.length} seleccionados</span></div><div className="ui-tabs" style={{marginTop:12}}><button className={type==="primary"?"active":""} onClick={()=>{setType("primary");setSelected([])}}>Primaria · Gestión → Central</button><button className={type==="secondary"?"active":""} onClick={()=>{setType("secondary");setSelected([])}}>Secundaria · Central → Histórico</button></div><label className="ui-field" style={{marginTop:12}}><span>Buscar</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Código, asunto o dependencia"/></label><div className="ui-list" style={{marginTop:12,maxHeight:420,overflow:"auto"}}>{candidates.length?candidates.map(x=><label className="ui-list-row" key={x.id} style={{cursor:"pointer"}}><span className="ui-list-main"><b>{x.title}</b><small>{x.expediente_code} · {x.organizational_units?.name} · Caja {(x.archive_folders||[]).find((f:any)=>f.box_id)?.archive_boxes?.box_number}</small></span><input type="checkbox" checked={selected.includes(x.id)} onChange={()=>toggle(x.id)}/></label>):<div className="ui-empty"><b>No hay candidatos</b><span>Solo aparecen expedientes con carpeta asignada a una caja y en la fase correspondiente.</span></div>}</div></section><aside className="ui-card pad ui-sticky"><div className="ui-section-head"><div><span>PASO 2</span><h3>Datos de transferencia</h3></div></div><form className="ui-form" style={{gridTemplateColumns:"1fr",marginTop:12}} onSubmit={save}><label className="ui-field"><span>Fecha</span><input type="date" name="transfer_date" defaultValue={today()}/></label><label className="ui-field"><span>Objeto</span><textarea name="object" required placeholder="Describe el objeto de la transferencia"/></label><label className="ui-field"><span>Recibe</span><input name="received_name" placeholder="Nombre del responsable receptor"/></label><label className="ui-field"><span>Observaciones</span><textarea name="notes"/></label><button className="ui-btn yellow" disabled={saving||!selected.length}>{saving?"Creando…":"Crear transferencia"}</button></form>{done&&<><div className="ui-divider"/><button className="ui-btn primary" onClick={print}>Imprimir D-FT-27</button></>}</aside></div>
 </UnifiedShell>
}
