"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import UnifiedShell from "@/components/UnifiedShell";
import { supabase } from "@/lib/supabase";
import type { Profile } from "@/lib/types";

type Row=Record<string,any>; type Mode="inicio"|"radicar"|"expediente";
const today=()=>new Date().toISOString().slice(0,10);

export default function WorkCenter(){
  const [profile,setProfile]=useState<Profile|null>(null); const [offices,setOffices]=useState<Row[]>([]); const [trd,setTrd]=useState<Row[]>([]); const [recent,setRecent]=useState<Row[]>([]); const [mode,setMode]=useState<Mode>("inicio"); const [officeId,setOfficeId]=useState(""); const [saving,setSaving]=useState(false); const [notice,setNotice]=useState("");
  useEffect(()=>{(async()=>{const {data:s}=await supabase.auth.getSession(); if(!s.session)return; const {data:p}=await supabase.from("profiles").select("*").eq("id",s.session.user.id).maybeSingle(); setProfile(p as Profile); const [u,t,e]=await Promise.all([supabase.from("organizational_units").select("id,name,code").eq("active",true).order("name"),supabase.from("trd_entries").select("id,office_id,name,level,system_code,official_code,disposition").in("level",["series","subseries"]).neq("review_state","rejected").order("name"),supabase.from("expedientes").select("id,expediente_code,title,status,phase,updated_at,organizational_units(name)").order("updated_at",{ascending:false}).limit(8)]); setOffices(u.data||[]);setTrd(t.data||[]);setRecent(e.data||[]);setOfficeId(p?.office_id||""); const q=new URLSearchParams(window.location.search).get("accion"); if(q==="radicar")setMode("radicar"); if(q==="expediente")setMode("expediente");})()},[]);
  const trdOptions=useMemo(()=>trd.filter(x=>!officeId||x.office_id===officeId),[trd,officeId]);
  function flash(x:string){setNotice(x);setTimeout(()=>setNotice(""),4200)}
  async function saveRad(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile?.organization_id)return;setSaving(true);const f=new FormData(e.currentTarget);const num=`RAD-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`;const {error}=await supabase.from("radications").insert({organization_id:profile.organization_id,office_id:f.get("office_id")||profile.office_id||null,radication_number:num,direction:f.get("direction"),channel:f.get("channel")||null,subject:String(f.get("subject")||"").trim(),sender:f.get("sender")||null,recipient:f.get("recipient")||null,received_or_sent_at:new Date(String(f.get("date")||today())+"T12:00:00").toISOString(),status:"open",metadata:{created_from:"work_center"}});setSaving(false);if(error)return flash(error.message);e.currentTarget.reset();flash(`Radicado ${num} creado correctamente.`);}
  async function saveExp(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile?.organization_id)return;setSaving(true);const f=new FormData(e.currentTarget);const oid=String(f.get("office_id")||profile.office_id||"");const office=offices.find(x=>x.id===oid);const tid=String(f.get("trd_entry_id")||"");const rule=trd.find(x=>x.id===tid);const code=`EI-${new Date().getFullYear()}-${office?.code||"EXP"}-${String(Date.now()).slice(-5)}`;const {data,error}=await supabase.from("expedientes").insert({organization_id:profile.organization_id,office_id:oid,trd_entry_id:tid,expediente_code:code,title:String(f.get("title")||"").trim(),description:f.get("description")||null,medium:f.get("medium")||"hybrid",phase:"management",status:"open",access_level:"internal",start_date:f.get("start_date")||today(),disposition:rule?.disposition||"pending",created_by:profile.id}).select("id").single();setSaving(false);if(error)return flash(error.message);flash(`Expediente ${code} creado.`);setTimeout(()=>{if(data?.id)window.location.href=`/trabajo/organizar?exp=${data.id}`},700);}
  return <UnifiedShell eyebrow="TRABAJO" title="Qué vas a hacer">
    <div className="ui-page-head"><div><span>OPERACIÓN</span><h2>Empieza por la tarea</h2><p>Solo elige la acción. La TRD y los formatos aparecen automáticamente cuando el proceso los necesita.</p></div>{mode!=="inicio"&&<button className="ui-btn secondary" onClick={()=>setMode("inicio")}>← Volver</button>}</div>
    {notice&&<div className="ui-callout ok" style={{marginBottom:12}}>{notice}</div>}
    {mode==="inicio"&&<>
      <div className="ui-grid cols-4">
        <button className="ui-card ui-action-card interactive" style={{border:0,textAlign:"left",cursor:"pointer"}} onClick={()=>setMode("radicar")}><div className="ui-action-icon">↗</div><h3>Radicar documento</h3><p>Entrada, salida o comunicación interna.</p><footer><span>Paso inicial</span><b>Empezar →</b></footer></button>
        <button className="ui-card ui-action-card interactive" style={{border:0,textAlign:"left",cursor:"pointer"}} onClick={()=>setMode("expediente")}><div className="ui-action-icon">＋</div><h3>Abrir expediente</h3><p>Crea el expediente y clasifícalo una sola vez con la TRD.</p><footer><span>Clasificación</span><b>Crear →</b></footer></button>
        <Link href="/trabajo/organizar" className="ui-card ui-action-card interactive"><div className="ui-action-icon">▱</div><h3>Organizar expediente</h3><p>Documentos → inventario → carpeta → caja → rótulo.</p><footer><span>Proceso guiado</span><b>Continuar →</b></footer></Link>
        <Link href="/archivo?vista=transferencias" className="ui-card ui-action-card interactive"><div className="ui-action-icon">⇄</div><h3>Transferir</h3><p>Mueve documentación organizada a archivo central o histórico.</p><footer><span>Archivo</span><b>Preparar →</b></footer></Link>
      </div>
      <section className="ui-section"><div className="ui-section-head"><div><span>CONTINUAR</span><h3>Expedientes recientes</h3></div></div><div className="ui-card ui-list">{recent.map(x=><Link key={x.id} href={`/trabajo/organizar?exp=${x.id}`} className="ui-list-row"><span className="ui-list-main"><b>{x.title}</b><small>{x.expediente_code} · {x.organizational_units?.name||"Sin dependencia"}</small></span><span className="ui-list-meta"><b>Continuar →</b><small>{x.status} · {x.phase}</small></span></Link>)}</div></section>
    </>}
    {mode==="radicar"&&<div className="ui-card pad" style={{maxWidth:850}}><div className="ui-section-head"><div><span>RADICACIÓN</span><h3>Registrar documento</h3></div><span className="ui-pill yellow">Número automático</span></div><form className="ui-form" onSubmit={saveRad}><label className="ui-field"><span>Tipo de movimiento</span><select name="direction" required><option value="inbound">Entrada</option><option value="outbound">Salida</option><option value="internal">Interna</option></select></label><label className="ui-field"><span>Dependencia responsable</span><select name="office_id" defaultValue={profile?.office_id||""} required><option value="">Selecciona</option>{offices.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label className="ui-field span-2"><span>Asunto</span><input name="subject" required placeholder="Describe claramente el asunto del documento"/></label><label className="ui-field"><span>Remitente</span><input name="sender" placeholder="Persona o entidad que envía"/></label><label className="ui-field"><span>Destinatario</span><input name="recipient" placeholder="Persona, área o entidad destino"/></label><label className="ui-field"><span>Canal</span><select name="channel"><option value="email">Correo electrónico</option><option value="physical">Físico</option><option value="web">Web</option><option value="internal">Interno</option></select></label><label className="ui-field"><span>Fecha</span><input type="date" name="date" defaultValue={today()} required/></label><div className="ui-field span-2"><button className="ui-btn yellow" disabled={saving}>{saving?"Guardando…":"Crear radicado"}</button></div></form></div>}
    {mode==="expediente"&&<div className="ui-card pad" style={{maxWidth:900}}><div className="ui-section-head"><div><span>NUEVO EXPEDIENTE</span><h3>Clasificar y abrir</h3></div><span className="ui-pill green">TRD obligatoria</span></div><div className="ui-callout info" style={{marginBottom:14}}>Selecciona la dependencia y después la Serie/Subserie. Esa clasificación quedará heredada por Hoja de control, FUID, carpeta, caja y transferencia.</div><form className="ui-form" onSubmit={saveExp}><label className="ui-field"><span>Dependencia</span><select name="office_id" value={officeId} onChange={e=>setOfficeId(e.target.value)} required><option value="">Selecciona</option>{offices.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="ui-field"><span>Clasificación TRD</span><select name="trd_entry_id" required disabled={!officeId}><option value="">Selecciona Serie/Subserie</option>{trdOptions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="ui-field span-2"><span>Nombre del expediente</span><input name="title" required placeholder="Ej. Contrato de mantenimiento sede principal 2026"/></label><label className="ui-field span-2"><span>Descripción</span><textarea name="description" placeholder="Descripción breve del asunto o trámite"/></label><label className="ui-field"><span>Medio</span><select name="medium"><option value="hybrid">Híbrido</option><option value="electronic">Electrónico</option><option value="physical">Físico</option></select></label><label className="ui-field"><span>Fecha de apertura</span><input type="date" name="start_date" defaultValue={today()}/></label><div className="ui-field span-2"><button className="ui-btn yellow" disabled={saving}>{saving?"Creando…":"Crear y empezar a organizar"}</button></div></form></div>}
  </UnifiedShell>
}
